<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>asciidoc</string>
    <key>scopeName</key>
    <string>source.asciidoc</string>
    <key>fileTypes</key>
    <array>
      <string>ad</string>
      <string>asc</string>
      <string>adoc</string>
      <string>asciidoc</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#inline</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#codeBlocks</string>
      </dict>
      <dict>
        <key>begin</key>
        <string>^={1,6}\p{Blank}+</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>markup.heading.asciidoc</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>$self</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\.(\w[\w ]*\w)</string>
        <key>end</key>
        <string>$</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>markup.heading.blocktitle.asciidoc</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>(\:)([^/\:\s]+)(\:)(\s+\S+)?$</string>
        <key>name</key>
        <string>support.constant.asciidoc</string>
        <key>captures</key>
        <dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.asciidoc</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^/{4,}$)</string>
        <key>end</key>
        <string>\1</string>
        <key>name</key>
        <string>comment.block.asciidoc</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(={4,})$</string>
        <key>end</key>
        <string>\1</string>
        <key>name</key>
        <string>markup.block.example.asciidoc</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\*{4,}$)</string>
        <key>end</key>
        <string>\1</string>
        <key>name</key>
        <string>markup.block.sidebar.asciidoc</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\.{4,}$)</string>
        <key>end</key>
        <string>\1</string>
        <key>name</key>
        <string>markup.block.literal.asciidoc</string>
        <key>patterns</key>
        <array/>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^\+{4,}$)</string>
        <key>end</key>
        <string>\1</string>
        <key>name</key>
        <string>markup.block.passthrough.asciidoc</string>
        <key>patterns</key>
        <array/>
      </dict>
      <dict>
        <key>begin</key>
        <string>^\[(quote|verse)(, ([\w ]+))?(, ([\w ]+))?</string>
        <key>end</key>
        <string>\]$</string>
        <key>beginCaptures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>markup.quote.declaration.asciidoc</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>markup.quote.attribution.asciidoc</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>markup.quote.citation.asciidoc</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>begin</key>
        <string>(^_{4,}$)</string>
        <key>end</key>
        <string>\1</string>
        <key>name</key>
        <string>markup.quote.block.asciidoc</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>^((NOTE|TIP|IMPORTANT|WARNING|CAUTION)\:)\p{Blank}+</string>
        <key>end</key>
        <string>$</string>
        <key>name</key>
        <string>markup.admonition.asciidoc</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.constant.asciidoc</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>^\[((normal|literal|listing|TIP|NOTE|IMPORTANT|WARNING|CAUTION|partintro|comment|example|sidebar|source|music|latex|graphviz))\]$</string>
        <key>name</key>
        <string>markup.explicit.asciidoc</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.constant.asciidoc</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>match</key>
        <string>^\[((sect[1-4]|abstract|preface|colophon|dedication|glossary|bibliography|synopsis|appendix|index))\]$</string>
        <key>name</key>
        <string>markup.section.asciidoc</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>support.constant.asciidoc</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>begin</key>
        <string>^(\|={3,}\s*)$</string>
        <key>beginCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.table.asciidoc</string>
          </dict>
        </dict>
        <key>end</key>
        <string>^\1$</string>
        <key>endCaptures</key>
        <dict>
          <key>0</key>
          <dict>
            <key>name</key>
            <string>support.table.asciidoc</string>
          </dict>
        </dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(^|\s+)([^\|\s\\]*)(\|)(?!={3,}|\|)</string>
            <key>captures</key>
            <dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>support.table.spec.asciidoc</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.table.asciidoc</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>include</key>
            <string>#inline</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>match</key>
        <string>^\s*([\*\-\.]{1,5})[ \t]+</string>
        <key>name</key>
        <string>markup.list.asciidoc</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>markup.list.bullet.asciidoc</string>
          </dict>
        </dict>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>inline</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)(\*[^\*]+\*)</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>markup.bold.asciidoc</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)(_[^_]+_)</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>markup.italic.asciidoc</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)({)([^/\:\s]+)(})</string>
            <key>name</key>
            <string>markup.substitution.asciidoc</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)(\[{2})([^\[\]]+)(\]{2})</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.blockid.asciidoc</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)(\[{3})([^\[\]]+)(\]{3})</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.biblioref.asciidoc</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)(\&lt;\&lt;)([^\&lt;\&gt;]+)(\&gt;\&gt;)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>markup.reference.asciidoc</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)`[^`]+`</string>
            <key>name</key>
            <string>markup.raw.inline.asciidoc</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(&amp;)(.+?)(;)</string>
            <key>name</key>
            <string>markup.htmlentity.asciidoc</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)([^:]+:)([^:].*?)(\[)([^\]]*?)(\])</string>
            <key>name</key>
            <string>markup.macro.inline.asciidoc</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)(\S+://\S+\.(com|net|org|edu|gov)(/\S+)?)</string>
            <key>name</key>
            <string>markup.underline.link.asciidoc</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?&lt;=^|\s)([^:]+:{2})(.+?)(\[)([^\]]*?)(\])</string>
            <key>name</key>
            <string>markup.macro.block.asciidoc</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
              <key>5</key>
              <dict>
                <key>name</key>
                <string>support.constant.asciidoc</string>
              </dict>
            </dict>
          </dict>
        </array>
      </dict>
      <key>codeBlocks</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*(javascript|js)\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.js</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*(ruby|rb)\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.ruby</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*go(lang)?\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.go</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.go</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*java\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.java</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*(markdown|mdown|md)\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.gfm</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.gfm</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*ya?ml\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.yaml</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.yaml</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*coffee-?(script)?\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.coffee</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.coffee</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*json\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.json</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.json</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*css\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                  <key>end</key>
                  <string>\1</string>
                  <key>endCaptures</key>
                  <dict>
                    <key>0</key>
                    <dict>
                      <key>name</key>
                      <string>support.asciidoc</string>
                    </dict>
                  </dict>
                  <key>contentName</key>
                  <string>source.css</string>
                  <key>patterns</key>
                  <array>
                    <dict>
                      <key>include</key>
                      <string>source.css</string>
                    </dict>
                  </array>
                </dict>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*less\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.css.less</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.css.less</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*xml\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>text.xml</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>text.xml</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*(rust|rs)\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.rust</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.rust</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*erlang\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.erlang</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.erlang</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*cs(harp)?\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.cs</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.cs</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*php\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.php</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.php</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*(sh|bash|shell)\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.shell</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.shell</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*py(thon)?\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.python</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.python</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*c\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.c</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.c</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*c(pp|\+\+)\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.cpp</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.cpp</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*(objc|objective-c)\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.objc</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.objc</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*swift\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.swift</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.swift</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*html\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>text.html.basic</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>text.html.basic</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*elixir\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.elixir</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.elixir</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*(diff|patch|rej)\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.diff</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.diff</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*julia\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.julia</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.julia</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*r\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.r</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.r</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*haskell\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.haskell</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.haskell</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*elm\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.elm</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.elm</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*sql\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.sql</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.sql</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source,\s*clojure\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>contentName</key>
                <string>source.clojure</string>
                <key>patterns</key>
                <array>
                  <dict>
                    <key>include</key>
                    <string>source.clojure</string>
                  </dict>
                </array>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^\[source(,[^\],]*)?\]$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^\s*$</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>begin</key>
                <string>(^\s*-{4,}\s*$)</string>
                <key>beginCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>end</key>
                <string>\1</string>
                <key>endCaptures</key>
                <dict>
                  <key>0</key>
                  <dict>
                    <key>name</key>
                    <string>support.asciidoc</string>
                  </dict>
                </dict>
                <key>name</key>
                <string>markup.raw.asciidoc</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*(javascript|js)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.js</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*(ruby|rb)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.ruby</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*go(lang)?\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.go</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*(markdown|mdown|md)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.gfm</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*ya?ml\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.yaml</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*coffee-?(script)?\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.coffee</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*json\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.json</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*css\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.css</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*less\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.css.less</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*xml\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.xml</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*(rust|rs)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.rust</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*erlang\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.erlang</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*cs(harp)?\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cs</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*php\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.php</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*(sh|bash|shell)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.shell</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*py(thon)?\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.python</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*c\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.c</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*c(pp|\+\+)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.cpp</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*(objc|objective-c)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.objc</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*swift\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.swift</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*html\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>text.html.basic</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*elixir\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.elixir</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*(diff|patch|rej)\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.diff</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*julia\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.julia</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*r\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.r</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*haskell\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.haskell</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*elm\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.elm</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*sql\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.sql</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}\s*clojure\s*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>source.clojure</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>begin</key>
            <string>^`{3,}.*$</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>end</key>
            <string>^`{3,}$</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>support.asciidoc</string>
              </dict>
            </dict>
            <key>name</key>
            <string>markup.raw.asciidoc</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
